ServerEvents.recipes(e=>{
    e.remove({output:'beyonddimensions:net_interface'})
    e.shaped('beyonddimensions:net_interface',[
        ' A ',
        'BCB'
    ],{
        A:'createutilities:graviton_tube',
        B:'beyonddimensions:space_time_stable_frame',
        C:'extendedae:ex_interface'
    }
    )
    e.replaceInput({output:'beyonddimensions:net_creater'},'minecraft:netherite_ingot','createutilities:void_steel_ingot')
    e.replaceInput({output:'beyonddimensions:net_pathway'},'minecraft:ender_eye','createutilities:graviton_tube')
    e.replaceInput({output:'beyonddimensions:net_ae_storage_cell'},'beyonddimensions:space_time_stable_frame','createutilities:graviton_tube')
    e.remove({output:'beyonddimensions:schematicannon_pathway'})
    e.shapeless('beyonddimensions:schematicannon_pathway',[
        'create:brass_block',
        'beyonddimensions:space_time_stable_frame',
        'create:schematic_table'])
    e.remove({output:'beyonddimensions:dimensional_connect_block'})
    e.recipes.create.deploying('beyonddimensions:dimensional_connect_block',
        [Ingredient.of('#c:stripped_logs'),Item.of('beyonddimensions:space_time_stable_frame')])
})
