StartupEvents.registry('item', e => {
    //注册物品
    e.create('circuit').displayName('电路板')
    e.create('graphite').displayName('石墨')
    e.create('logistics_toolbox').displayName('物流工具箱')
    e.create('fluid_toolbox').displayName('液流工具箱')
    e.create('infinite_heat_bar').displayName('无限加热燃料棒').rarity('uncommon')
    e.create('infinite_superheat_bar').displayName('无限超级加热燃料棒').rarity("epic")
    e.create('steel_sheet').displayName('钢板')

})
ItemEvents.modification(e=>{
    e.modify('createbigcannons:steel_block',i=>{
        i.setItemName(Text.translatable("tag.createbigcannons.block_steel"))
    })
    e.modify('kubejs:tar_bucket',i=>{
        i.setCraftingRemainder('minecraft:bucket')
    })
    e.modify('createdieselgenerators:gasoline_bucket',i=>{
        i.setFood(20,1)
        i.modifyFood(builder=>{
            builder.usingConvertsTo('minecraft:bucket')
        })
    })
    e.modify('minecraft:dirt',i=>{
        i.setFood(4,0.25)
        i.modifyFood(builder=>{
            builder.saturation(0.25)
            builder.effect('minecraft:nausea',200,1,0.25)
            builder.eatSeconds(10)
        })
    })
})
