#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 07 01:06:24 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Helian-mmco_Sundial-Lite_edit-0.6.8
