version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
logisticsnetworks = true
farmersdelight = true
create_mechanical_extruder = true
drivebywire = true
createpropulsion = true
redstonepen = true
vintageimprovements = true
copycats = true
dndecor = true
createutilities = true
createdieselgenerators = true
create_aeronautics_automated_logistics = true
fluidlogistics = true
create_enchantment_industry = true
aeronautics_utility_objects = true
mekanismgenerators = true
escalated = true
railways = true
create_rns = true
industrial_platform = true
mynethersdelight = true
ftbquests = true
functionalstorage = true
aero_reformation = true
electroenergetics = true
create_radar = true
sophisticatedbackpacks = true
appflux = true
dndesires = true
offroad = true
createbigcannons = true
drivebywiretypewriter = true
createprism = true
create = true
create_fantasizing = true
mekanism = true
ldlib2 = true
mbd2 = true
aeronautics = true
create_aeronautics_toolgun = true
simulated = true
vsfluidlink = true
createadditionallogistics = true
createoreexcavation = true
minecraft = true
createphantom = true
create_dragons_plus = true
create_connected = true
createdeco = true
createaddition = true
ratatouille = true
ae2 = true
waystones = true
create_mobile_packages = true
dragonlib = true
createsifter = true
extendedae = true
mekmm = true
delighto_flight = true
create_integrated_farming = true
aeroworks = true
create_power_loader = true
